#!/usr/bin/env python3

import graph

import os
import pathlib
import argparse
import json


def main():
    parser = argparse.ArgumentParser("json2topo")
    parser.add_argument("file", nargs='+', help="File(s) to convert")
    parser.add_argument('-o', '--output', type=pathlib.Path, default=None, help="output file for converting a single file")
    parser.add_argument('-O', '--output-dir', type=pathlib.Path, default=None, help="output directory for converting multiple files")
    args = parser.parse_args()

    if len(args.file) > 1 and args.output:
        raise ValueError("Option '--output' does not support converting multiple files")

    for json_name in args.file:
        topo_path = ""

        if args.output:
            topo_path = args.output
        else:
            topo_path = os.path.splitext(json_name)[0] + '.txt'

        if args.output_dir:
            topo_path = os.path.join(args.output_dir, topo_path)

        with open(topo_path, "w") as topo_file, open(json_name, "r") as json_file:
            topo_json = json.load(json_file)
            topo = graph.Topology.from_dict(topo_json)
            topo_file.write("# generated by topo2json.py\n\n")
            topo.write_txt(topo_file)


if __name__ == '__main__':
    main()
