/* -*- Mode:C++; c-file-style:"gnu"; indent-tabs-mode:nil; -*- */
/**
 * Copyright (c) 2011-2015  Regents of the University of California.
 *
 * This file is part of ndnSIM. See AUTHORS for complete list of ndnSIM authors and
 * contributors.
 *
 * ndnSIM is free software: you can redistribute it and/or modify it under the terms
 * of the GNU General Public License as published by the Free Software Foundation,
 * either version 3 of the License, or (at your option) any later version.
 *
 * ndnSIM is distributed in the hope that it will be useful, but WITHOUT ANY WARRANTY;
 * without even the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
 * PURPOSE.  See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License along with
 * ndnSIM, e.g., in COPYING.md file.  If not, see <http://www.gnu.org/licenses/>.
 **/

// ndn-custom-apps.cpp

#include "ns3/core-module.h"
#include "ns3/network-module.h"
#include "ns3/ndnSIM-module.h"
#include "ns3/string.h"

#define PREFIX "/nescoSCOPT"

namespace ns3 {

int
main(int argc, char* argv[])
{
  // Read optional command-line parameters (e.g., enable visualizer with ./waf --run=<> --visualize
  CommandLine cmd;
  cmd.Parse(argc, argv);

  // Creating nodes
  AnnotatedTopologyReader topologyReader("", 1);
  topologyReader.SetFileName("topologies/topo-cabeee-cpm-x_500.txt");
  topologyReader.Read();




  // Install NDN stack on all nodes
  ndn::StackHelper ndnHelper;
  ndnHelper.setPolicy("nfd::cs::lru");
  //ndnHelper.setCsSize(100);
  //ndnHelper.setCsSize(1);
  ndnHelper.SetDefaultRoutes(true);

  //ndnHelper.InstallAll();

  // Getting containers for the nodes
  Ptr<Node> producer = Names::Find<Node>("sensor");
  Ptr<Node> rtr001 = Names::Find<Node>("rtr-001");
  Ptr<Node> rtr002 = Names::Find<Node>("rtr-002");
  Ptr<Node> rtr003 = Names::Find<Node>("rtr-003");
  Ptr<Node> rtr004 = Names::Find<Node>("rtr-004");
  Ptr<Node> rtr005 = Names::Find<Node>("rtr-005");
  Ptr<Node> rtr006 = Names::Find<Node>("rtr-006");
  Ptr<Node> rtr007 = Names::Find<Node>("rtr-007");
  Ptr<Node> rtr008 = Names::Find<Node>("rtr-008");
  Ptr<Node> rtr009 = Names::Find<Node>("rtr-009");
  Ptr<Node> rtr010 = Names::Find<Node>("rtr-010");
  Ptr<Node> rtr011 = Names::Find<Node>("rtr-011");
  Ptr<Node> rtr012 = Names::Find<Node>("rtr-012");
  Ptr<Node> rtr013 = Names::Find<Node>("rtr-013");
  Ptr<Node> rtr014 = Names::Find<Node>("rtr-014");
  Ptr<Node> rtr015 = Names::Find<Node>("rtr-015");
  Ptr<Node> rtr016 = Names::Find<Node>("rtr-016");
  Ptr<Node> rtr017 = Names::Find<Node>("rtr-017");
  Ptr<Node> rtr018 = Names::Find<Node>("rtr-018");
  Ptr<Node> rtr019 = Names::Find<Node>("rtr-019");
  Ptr<Node> rtr020 = Names::Find<Node>("rtr-020");
  Ptr<Node> rtr021 = Names::Find<Node>("rtr-021");
  Ptr<Node> rtr022 = Names::Find<Node>("rtr-022");
  Ptr<Node> rtr023 = Names::Find<Node>("rtr-023");
  Ptr<Node> rtr024 = Names::Find<Node>("rtr-024");
  Ptr<Node> rtr025 = Names::Find<Node>("rtr-025");
  Ptr<Node> rtr026 = Names::Find<Node>("rtr-026");
  Ptr<Node> rtr027 = Names::Find<Node>("rtr-027");
  Ptr<Node> rtr028 = Names::Find<Node>("rtr-028");
  Ptr<Node> rtr029 = Names::Find<Node>("rtr-029");
  Ptr<Node> rtr030 = Names::Find<Node>("rtr-030");
  Ptr<Node> rtr031 = Names::Find<Node>("rtr-031");
  Ptr<Node> rtr032 = Names::Find<Node>("rtr-032");
  Ptr<Node> rtr033 = Names::Find<Node>("rtr-033");
  Ptr<Node> rtr034 = Names::Find<Node>("rtr-034");
  Ptr<Node> rtr035 = Names::Find<Node>("rtr-035");
  Ptr<Node> rtr036 = Names::Find<Node>("rtr-036");
  Ptr<Node> rtr037 = Names::Find<Node>("rtr-037");
  Ptr<Node> rtr038 = Names::Find<Node>("rtr-038");
  Ptr<Node> rtr039 = Names::Find<Node>("rtr-039");
  Ptr<Node> rtr040 = Names::Find<Node>("rtr-040");
  Ptr<Node> rtr041 = Names::Find<Node>("rtr-041");
  Ptr<Node> rtr042 = Names::Find<Node>("rtr-042");
  Ptr<Node> rtr043 = Names::Find<Node>("rtr-043");
  Ptr<Node> rtr044 = Names::Find<Node>("rtr-044");
  Ptr<Node> rtr045 = Names::Find<Node>("rtr-045");
  Ptr<Node> rtr046 = Names::Find<Node>("rtr-046");
  Ptr<Node> rtr047 = Names::Find<Node>("rtr-047");
  Ptr<Node> rtr048 = Names::Find<Node>("rtr-048");
  Ptr<Node> rtr049 = Names::Find<Node>("rtr-049");
  Ptr<Node> rtr050 = Names::Find<Node>("rtr-050");
  Ptr<Node> rtr051 = Names::Find<Node>("rtr-051");
  Ptr<Node> rtr052 = Names::Find<Node>("rtr-052");
  Ptr<Node> rtr053 = Names::Find<Node>("rtr-053");
  Ptr<Node> rtr054 = Names::Find<Node>("rtr-054");
  Ptr<Node> rtr055 = Names::Find<Node>("rtr-055");
  Ptr<Node> rtr056 = Names::Find<Node>("rtr-056");
  Ptr<Node> rtr057 = Names::Find<Node>("rtr-057");
  Ptr<Node> rtr058 = Names::Find<Node>("rtr-058");
  Ptr<Node> rtr059 = Names::Find<Node>("rtr-059");
  Ptr<Node> rtr060 = Names::Find<Node>("rtr-060");
  Ptr<Node> rtr061 = Names::Find<Node>("rtr-061");
  Ptr<Node> rtr062 = Names::Find<Node>("rtr-062");
  Ptr<Node> rtr063 = Names::Find<Node>("rtr-063");
  Ptr<Node> rtr064 = Names::Find<Node>("rtr-064");
  Ptr<Node> rtr065 = Names::Find<Node>("rtr-065");
  Ptr<Node> rtr066 = Names::Find<Node>("rtr-066");
  Ptr<Node> rtr067 = Names::Find<Node>("rtr-067");
  Ptr<Node> rtr068 = Names::Find<Node>("rtr-068");
  Ptr<Node> rtr069 = Names::Find<Node>("rtr-069");
  Ptr<Node> rtr070 = Names::Find<Node>("rtr-070");
  Ptr<Node> rtr071 = Names::Find<Node>("rtr-071");
  Ptr<Node> rtr072 = Names::Find<Node>("rtr-072");
  Ptr<Node> rtr073 = Names::Find<Node>("rtr-073");
  Ptr<Node> rtr074 = Names::Find<Node>("rtr-074");
  Ptr<Node> rtr075 = Names::Find<Node>("rtr-075");
  Ptr<Node> rtr076 = Names::Find<Node>("rtr-076");
  Ptr<Node> rtr077 = Names::Find<Node>("rtr-077");
  Ptr<Node> rtr078 = Names::Find<Node>("rtr-078");
  Ptr<Node> rtr079 = Names::Find<Node>("rtr-079");
  Ptr<Node> rtr080 = Names::Find<Node>("rtr-080");
  Ptr<Node> rtr081 = Names::Find<Node>("rtr-081");
  Ptr<Node> rtr082 = Names::Find<Node>("rtr-082");
  Ptr<Node> rtr083 = Names::Find<Node>("rtr-083");
  Ptr<Node> rtr084 = Names::Find<Node>("rtr-084");
  Ptr<Node> rtr085 = Names::Find<Node>("rtr-085");
  Ptr<Node> rtr086 = Names::Find<Node>("rtr-086");
  Ptr<Node> rtr087 = Names::Find<Node>("rtr-087");
  Ptr<Node> rtr088 = Names::Find<Node>("rtr-088");
  Ptr<Node> rtr089 = Names::Find<Node>("rtr-089");
  Ptr<Node> rtr090 = Names::Find<Node>("rtr-090");
  Ptr<Node> rtr091 = Names::Find<Node>("rtr-091");
  Ptr<Node> rtr092 = Names::Find<Node>("rtr-092");
  Ptr<Node> rtr093 = Names::Find<Node>("rtr-093");
  Ptr<Node> rtr094 = Names::Find<Node>("rtr-094");
  Ptr<Node> rtr095 = Names::Find<Node>("rtr-095");
  Ptr<Node> rtr096 = Names::Find<Node>("rtr-096");
  Ptr<Node> rtr097 = Names::Find<Node>("rtr-097");
  Ptr<Node> rtr098 = Names::Find<Node>("rtr-098");
  Ptr<Node> rtr099 = Names::Find<Node>("rtr-099");
  Ptr<Node> rtr100 = Names::Find<Node>("rtr-100");
  Ptr<Node> rtr101 = Names::Find<Node>("rtr-101");
  Ptr<Node> rtr102 = Names::Find<Node>("rtr-102");
  Ptr<Node> rtr103 = Names::Find<Node>("rtr-103");
  Ptr<Node> rtr104 = Names::Find<Node>("rtr-104");
  Ptr<Node> rtr105 = Names::Find<Node>("rtr-105");
  Ptr<Node> rtr106 = Names::Find<Node>("rtr-106");
  Ptr<Node> rtr107 = Names::Find<Node>("rtr-107");
  Ptr<Node> rtr108 = Names::Find<Node>("rtr-108");
  Ptr<Node> rtr109 = Names::Find<Node>("rtr-109");
  Ptr<Node> rtr110 = Names::Find<Node>("rtr-110");
  Ptr<Node> rtr111 = Names::Find<Node>("rtr-111");
  Ptr<Node> rtr112 = Names::Find<Node>("rtr-112");
  Ptr<Node> rtr113 = Names::Find<Node>("rtr-113");
  Ptr<Node> rtr114 = Names::Find<Node>("rtr-114");
  Ptr<Node> rtr115 = Names::Find<Node>("rtr-115");
  Ptr<Node> rtr116 = Names::Find<Node>("rtr-116");
  Ptr<Node> rtr117 = Names::Find<Node>("rtr-117");
  Ptr<Node> rtr118 = Names::Find<Node>("rtr-118");
  Ptr<Node> rtr119 = Names::Find<Node>("rtr-119");
  Ptr<Node> rtr120 = Names::Find<Node>("rtr-120");
  Ptr<Node> rtr121 = Names::Find<Node>("rtr-121");
  Ptr<Node> rtr122 = Names::Find<Node>("rtr-122");
  Ptr<Node> rtr123 = Names::Find<Node>("rtr-123");
  Ptr<Node> rtr124 = Names::Find<Node>("rtr-124");
  Ptr<Node> rtr125 = Names::Find<Node>("rtr-125");
  Ptr<Node> rtr126 = Names::Find<Node>("rtr-126");
  Ptr<Node> rtr127 = Names::Find<Node>("rtr-127");
  Ptr<Node> rtr128 = Names::Find<Node>("rtr-128");
  Ptr<Node> rtr129 = Names::Find<Node>("rtr-129");
  Ptr<Node> rtr130 = Names::Find<Node>("rtr-130");
  Ptr<Node> rtr131 = Names::Find<Node>("rtr-131");
  Ptr<Node> rtr132 = Names::Find<Node>("rtr-132");
  Ptr<Node> rtr133 = Names::Find<Node>("rtr-133");
  Ptr<Node> rtr134 = Names::Find<Node>("rtr-134");
  Ptr<Node> rtr135 = Names::Find<Node>("rtr-135");
  Ptr<Node> rtr136 = Names::Find<Node>("rtr-136");
  Ptr<Node> rtr137 = Names::Find<Node>("rtr-137");
  Ptr<Node> rtr138 = Names::Find<Node>("rtr-138");
  Ptr<Node> rtr139 = Names::Find<Node>("rtr-139");
  Ptr<Node> rtr140 = Names::Find<Node>("rtr-140");
  Ptr<Node> rtr141 = Names::Find<Node>("rtr-141");
  Ptr<Node> rtr142 = Names::Find<Node>("rtr-142");
  Ptr<Node> rtr143 = Names::Find<Node>("rtr-143");
  Ptr<Node> rtr144 = Names::Find<Node>("rtr-144");
  Ptr<Node> rtr145 = Names::Find<Node>("rtr-145");
  Ptr<Node> rtr146 = Names::Find<Node>("rtr-146");
  Ptr<Node> rtr147 = Names::Find<Node>("rtr-147");
  Ptr<Node> rtr148 = Names::Find<Node>("rtr-148");
  Ptr<Node> rtr149 = Names::Find<Node>("rtr-149");
  Ptr<Node> rtr150 = Names::Find<Node>("rtr-150");
  Ptr<Node> rtr151 = Names::Find<Node>("rtr-151");
  Ptr<Node> rtr152 = Names::Find<Node>("rtr-152");
  Ptr<Node> rtr153 = Names::Find<Node>("rtr-153");
  Ptr<Node> rtr154 = Names::Find<Node>("rtr-154");
  Ptr<Node> rtr155 = Names::Find<Node>("rtr-155");
  Ptr<Node> rtr156 = Names::Find<Node>("rtr-156");
  Ptr<Node> rtr157 = Names::Find<Node>("rtr-157");
  Ptr<Node> rtr158 = Names::Find<Node>("rtr-158");
  Ptr<Node> rtr159 = Names::Find<Node>("rtr-159");
  Ptr<Node> rtr160 = Names::Find<Node>("rtr-160");
  Ptr<Node> rtr161 = Names::Find<Node>("rtr-161");
  Ptr<Node> rtr162 = Names::Find<Node>("rtr-162");
  Ptr<Node> rtr163 = Names::Find<Node>("rtr-163");
  Ptr<Node> rtr164 = Names::Find<Node>("rtr-164");
  Ptr<Node> rtr165 = Names::Find<Node>("rtr-165");
  Ptr<Node> rtr166 = Names::Find<Node>("rtr-166");
  Ptr<Node> rtr167 = Names::Find<Node>("rtr-167");
  Ptr<Node> rtr168 = Names::Find<Node>("rtr-168");
  Ptr<Node> rtr169 = Names::Find<Node>("rtr-169");
  Ptr<Node> rtr170 = Names::Find<Node>("rtr-170");
  Ptr<Node> rtr171 = Names::Find<Node>("rtr-171");
  Ptr<Node> rtr172 = Names::Find<Node>("rtr-172");
  Ptr<Node> rtr173 = Names::Find<Node>("rtr-173");
  Ptr<Node> rtr174 = Names::Find<Node>("rtr-174");
  Ptr<Node> rtr175 = Names::Find<Node>("rtr-175");
  Ptr<Node> rtr176 = Names::Find<Node>("rtr-176");
  Ptr<Node> rtr177 = Names::Find<Node>("rtr-177");
  Ptr<Node> rtr178 = Names::Find<Node>("rtr-178");
  Ptr<Node> rtr179 = Names::Find<Node>("rtr-179");
  Ptr<Node> rtr180 = Names::Find<Node>("rtr-180");
  Ptr<Node> rtr181 = Names::Find<Node>("rtr-181");
  Ptr<Node> rtr182 = Names::Find<Node>("rtr-182");
  Ptr<Node> rtr183 = Names::Find<Node>("rtr-183");
  Ptr<Node> rtr184 = Names::Find<Node>("rtr-184");
  Ptr<Node> rtr185 = Names::Find<Node>("rtr-185");
  Ptr<Node> rtr186 = Names::Find<Node>("rtr-186");
  Ptr<Node> rtr187 = Names::Find<Node>("rtr-187");
  Ptr<Node> rtr188 = Names::Find<Node>("rtr-188");
  Ptr<Node> rtr189 = Names::Find<Node>("rtr-189");
  Ptr<Node> rtr190 = Names::Find<Node>("rtr-190");
  Ptr<Node> rtr191 = Names::Find<Node>("rtr-191");
  Ptr<Node> rtr192 = Names::Find<Node>("rtr-192");
  Ptr<Node> rtr193 = Names::Find<Node>("rtr-193");
  Ptr<Node> rtr194 = Names::Find<Node>("rtr-194");
  Ptr<Node> rtr195 = Names::Find<Node>("rtr-195");
  Ptr<Node> rtr196 = Names::Find<Node>("rtr-196");
  Ptr<Node> rtr197 = Names::Find<Node>("rtr-197");
  Ptr<Node> rtr198 = Names::Find<Node>("rtr-198");
  Ptr<Node> rtr199 = Names::Find<Node>("rtr-199");
  Ptr<Node> rtr200 = Names::Find<Node>("rtr-200");
  Ptr<Node> rtr201 = Names::Find<Node>("rtr-201");
  Ptr<Node> rtr202 = Names::Find<Node>("rtr-202");
  Ptr<Node> rtr203 = Names::Find<Node>("rtr-203");
  Ptr<Node> rtr204 = Names::Find<Node>("rtr-204");
  Ptr<Node> rtr205 = Names::Find<Node>("rtr-205");
  Ptr<Node> rtr206 = Names::Find<Node>("rtr-206");
  Ptr<Node> rtr207 = Names::Find<Node>("rtr-207");
  Ptr<Node> rtr208 = Names::Find<Node>("rtr-208");
  Ptr<Node> rtr209 = Names::Find<Node>("rtr-209");
  Ptr<Node> rtr210 = Names::Find<Node>("rtr-210");
  Ptr<Node> rtr211 = Names::Find<Node>("rtr-211");
  Ptr<Node> rtr212 = Names::Find<Node>("rtr-212");
  Ptr<Node> rtr213 = Names::Find<Node>("rtr-213");
  Ptr<Node> rtr214 = Names::Find<Node>("rtr-214");
  Ptr<Node> rtr215 = Names::Find<Node>("rtr-215");
  Ptr<Node> rtr216 = Names::Find<Node>("rtr-216");
  Ptr<Node> rtr217 = Names::Find<Node>("rtr-217");
  Ptr<Node> rtr218 = Names::Find<Node>("rtr-218");
  Ptr<Node> rtr219 = Names::Find<Node>("rtr-219");
  Ptr<Node> rtr220 = Names::Find<Node>("rtr-220");
  Ptr<Node> rtr221 = Names::Find<Node>("rtr-221");
  Ptr<Node> rtr222 = Names::Find<Node>("rtr-222");
  Ptr<Node> rtr223 = Names::Find<Node>("rtr-223");
  Ptr<Node> rtr224 = Names::Find<Node>("rtr-224");
  Ptr<Node> rtr225 = Names::Find<Node>("rtr-225");
  Ptr<Node> rtr226 = Names::Find<Node>("rtr-226");
  Ptr<Node> rtr227 = Names::Find<Node>("rtr-227");
  Ptr<Node> rtr228 = Names::Find<Node>("rtr-228");
  Ptr<Node> rtr229 = Names::Find<Node>("rtr-229");
  Ptr<Node> rtr230 = Names::Find<Node>("rtr-230");
  Ptr<Node> rtr231 = Names::Find<Node>("rtr-231");
  Ptr<Node> rtr232 = Names::Find<Node>("rtr-232");
  Ptr<Node> rtr233 = Names::Find<Node>("rtr-233");
  Ptr<Node> rtr234 = Names::Find<Node>("rtr-234");
  Ptr<Node> rtr235 = Names::Find<Node>("rtr-235");
  Ptr<Node> rtr236 = Names::Find<Node>("rtr-236");
  Ptr<Node> rtr237 = Names::Find<Node>("rtr-237");
  Ptr<Node> rtr238 = Names::Find<Node>("rtr-238");
  Ptr<Node> rtr239 = Names::Find<Node>("rtr-239");
  Ptr<Node> rtr240 = Names::Find<Node>("rtr-240");
  Ptr<Node> rtr241 = Names::Find<Node>("rtr-241");
  Ptr<Node> rtr242 = Names::Find<Node>("rtr-242");
  Ptr<Node> rtr243 = Names::Find<Node>("rtr-243");
  Ptr<Node> rtr244 = Names::Find<Node>("rtr-244");
  Ptr<Node> rtr245 = Names::Find<Node>("rtr-245");
  Ptr<Node> rtr246 = Names::Find<Node>("rtr-246");
  Ptr<Node> rtr247 = Names::Find<Node>("rtr-247");
  Ptr<Node> rtr248 = Names::Find<Node>("rtr-248");
  Ptr<Node> rtr249 = Names::Find<Node>("rtr-249");
  Ptr<Node> rtr250 = Names::Find<Node>("rtr-250");
  Ptr<Node> rtr251 = Names::Find<Node>("rtr-251");
  Ptr<Node> rtr252 = Names::Find<Node>("rtr-252");
  Ptr<Node> rtr253 = Names::Find<Node>("rtr-253");
  Ptr<Node> rtr254 = Names::Find<Node>("rtr-254");
  Ptr<Node> rtr255 = Names::Find<Node>("rtr-255");
  Ptr<Node> rtr256 = Names::Find<Node>("rtr-256");
  Ptr<Node> rtr257 = Names::Find<Node>("rtr-257");
  Ptr<Node> rtr258 = Names::Find<Node>("rtr-258");
  Ptr<Node> rtr259 = Names::Find<Node>("rtr-259");
  Ptr<Node> rtr260 = Names::Find<Node>("rtr-260");
  Ptr<Node> rtr261 = Names::Find<Node>("rtr-261");
  Ptr<Node> rtr262 = Names::Find<Node>("rtr-262");
  Ptr<Node> rtr263 = Names::Find<Node>("rtr-263");
  Ptr<Node> rtr264 = Names::Find<Node>("rtr-264");
  Ptr<Node> rtr265 = Names::Find<Node>("rtr-265");
  Ptr<Node> rtr266 = Names::Find<Node>("rtr-266");
  Ptr<Node> rtr267 = Names::Find<Node>("rtr-267");
  Ptr<Node> rtr268 = Names::Find<Node>("rtr-268");
  Ptr<Node> rtr269 = Names::Find<Node>("rtr-269");
  Ptr<Node> rtr270 = Names::Find<Node>("rtr-270");
  Ptr<Node> rtr271 = Names::Find<Node>("rtr-271");
  Ptr<Node> rtr272 = Names::Find<Node>("rtr-272");
  Ptr<Node> rtr273 = Names::Find<Node>("rtr-273");
  Ptr<Node> rtr274 = Names::Find<Node>("rtr-274");
  Ptr<Node> rtr275 = Names::Find<Node>("rtr-275");
  Ptr<Node> rtr276 = Names::Find<Node>("rtr-276");
  Ptr<Node> rtr277 = Names::Find<Node>("rtr-277");
  Ptr<Node> rtr278 = Names::Find<Node>("rtr-278");
  Ptr<Node> rtr279 = Names::Find<Node>("rtr-279");
  Ptr<Node> rtr280 = Names::Find<Node>("rtr-280");
  Ptr<Node> rtr281 = Names::Find<Node>("rtr-281");
  Ptr<Node> rtr282 = Names::Find<Node>("rtr-282");
  Ptr<Node> rtr283 = Names::Find<Node>("rtr-283");
  Ptr<Node> rtr284 = Names::Find<Node>("rtr-284");
  Ptr<Node> rtr285 = Names::Find<Node>("rtr-285");
  Ptr<Node> rtr286 = Names::Find<Node>("rtr-286");
  Ptr<Node> rtr287 = Names::Find<Node>("rtr-287");
  Ptr<Node> rtr288 = Names::Find<Node>("rtr-288");
  Ptr<Node> rtr289 = Names::Find<Node>("rtr-289");
  Ptr<Node> rtr290 = Names::Find<Node>("rtr-290");
  Ptr<Node> rtr291 = Names::Find<Node>("rtr-291");
  Ptr<Node> rtr292 = Names::Find<Node>("rtr-292");
  Ptr<Node> rtr293 = Names::Find<Node>("rtr-293");
  Ptr<Node> rtr294 = Names::Find<Node>("rtr-294");
  Ptr<Node> rtr295 = Names::Find<Node>("rtr-295");
  Ptr<Node> rtr296 = Names::Find<Node>("rtr-296");
  Ptr<Node> rtr297 = Names::Find<Node>("rtr-297");
  Ptr<Node> rtr298 = Names::Find<Node>("rtr-298");
  Ptr<Node> rtr299 = Names::Find<Node>("rtr-299");
  Ptr<Node> rtr300 = Names::Find<Node>("rtr-300");
  Ptr<Node> rtr301 = Names::Find<Node>("rtr-301");
  Ptr<Node> rtr302 = Names::Find<Node>("rtr-302");
  Ptr<Node> rtr303 = Names::Find<Node>("rtr-303");
  Ptr<Node> rtr304 = Names::Find<Node>("rtr-304");
  Ptr<Node> rtr305 = Names::Find<Node>("rtr-305");
  Ptr<Node> rtr306 = Names::Find<Node>("rtr-306");
  Ptr<Node> rtr307 = Names::Find<Node>("rtr-307");
  Ptr<Node> rtr308 = Names::Find<Node>("rtr-308");
  Ptr<Node> rtr309 = Names::Find<Node>("rtr-309");
  Ptr<Node> rtr310 = Names::Find<Node>("rtr-310");
  Ptr<Node> rtr311 = Names::Find<Node>("rtr-311");
  Ptr<Node> rtr312 = Names::Find<Node>("rtr-312");
  Ptr<Node> rtr313 = Names::Find<Node>("rtr-313");
  Ptr<Node> rtr314 = Names::Find<Node>("rtr-314");
  Ptr<Node> rtr315 = Names::Find<Node>("rtr-315");
  Ptr<Node> rtr316 = Names::Find<Node>("rtr-316");
  Ptr<Node> rtr317 = Names::Find<Node>("rtr-317");
  Ptr<Node> rtr318 = Names::Find<Node>("rtr-318");
  Ptr<Node> rtr319 = Names::Find<Node>("rtr-319");
  Ptr<Node> rtr320 = Names::Find<Node>("rtr-320");
  Ptr<Node> rtr321 = Names::Find<Node>("rtr-321");
  Ptr<Node> rtr322 = Names::Find<Node>("rtr-322");
  Ptr<Node> rtr323 = Names::Find<Node>("rtr-323");
  Ptr<Node> rtr324 = Names::Find<Node>("rtr-324");
  Ptr<Node> rtr325 = Names::Find<Node>("rtr-325");
  Ptr<Node> rtr326 = Names::Find<Node>("rtr-326");
  Ptr<Node> rtr327 = Names::Find<Node>("rtr-327");
  Ptr<Node> rtr328 = Names::Find<Node>("rtr-328");
  Ptr<Node> rtr329 = Names::Find<Node>("rtr-329");
  Ptr<Node> rtr330 = Names::Find<Node>("rtr-330");
  Ptr<Node> rtr331 = Names::Find<Node>("rtr-331");
  Ptr<Node> rtr332 = Names::Find<Node>("rtr-332");
  Ptr<Node> rtr333 = Names::Find<Node>("rtr-333");
  Ptr<Node> rtr334 = Names::Find<Node>("rtr-334");
  Ptr<Node> rtr335 = Names::Find<Node>("rtr-335");
  Ptr<Node> rtr336 = Names::Find<Node>("rtr-336");
  Ptr<Node> rtr337 = Names::Find<Node>("rtr-337");
  Ptr<Node> rtr338 = Names::Find<Node>("rtr-338");
  Ptr<Node> rtr339 = Names::Find<Node>("rtr-339");
  Ptr<Node> rtr340 = Names::Find<Node>("rtr-340");
  Ptr<Node> rtr341 = Names::Find<Node>("rtr-341");
  Ptr<Node> rtr342 = Names::Find<Node>("rtr-342");
  Ptr<Node> rtr343 = Names::Find<Node>("rtr-343");
  Ptr<Node> rtr344 = Names::Find<Node>("rtr-344");
  Ptr<Node> rtr345 = Names::Find<Node>("rtr-345");
  Ptr<Node> rtr346 = Names::Find<Node>("rtr-346");
  Ptr<Node> rtr347 = Names::Find<Node>("rtr-347");
  Ptr<Node> rtr348 = Names::Find<Node>("rtr-348");
  Ptr<Node> rtr349 = Names::Find<Node>("rtr-349");
  Ptr<Node> rtr350 = Names::Find<Node>("rtr-350");
  Ptr<Node> rtr351 = Names::Find<Node>("rtr-351");
  Ptr<Node> rtr352 = Names::Find<Node>("rtr-352");
  Ptr<Node> rtr353 = Names::Find<Node>("rtr-353");
  Ptr<Node> rtr354 = Names::Find<Node>("rtr-354");
  Ptr<Node> rtr355 = Names::Find<Node>("rtr-355");
  Ptr<Node> rtr356 = Names::Find<Node>("rtr-356");
  Ptr<Node> rtr357 = Names::Find<Node>("rtr-357");
  Ptr<Node> rtr358 = Names::Find<Node>("rtr-358");
  Ptr<Node> rtr359 = Names::Find<Node>("rtr-359");
  Ptr<Node> rtr360 = Names::Find<Node>("rtr-360");
  Ptr<Node> rtr361 = Names::Find<Node>("rtr-361");
  Ptr<Node> rtr362 = Names::Find<Node>("rtr-362");
  Ptr<Node> rtr363 = Names::Find<Node>("rtr-363");
  Ptr<Node> rtr364 = Names::Find<Node>("rtr-364");
  Ptr<Node> rtr365 = Names::Find<Node>("rtr-365");
  Ptr<Node> rtr366 = Names::Find<Node>("rtr-366");
  Ptr<Node> rtr367 = Names::Find<Node>("rtr-367");
  Ptr<Node> rtr368 = Names::Find<Node>("rtr-368");
  Ptr<Node> rtr369 = Names::Find<Node>("rtr-369");
  Ptr<Node> rtr370 = Names::Find<Node>("rtr-370");
  Ptr<Node> rtr371 = Names::Find<Node>("rtr-371");
  Ptr<Node> rtr372 = Names::Find<Node>("rtr-372");
  Ptr<Node> rtr373 = Names::Find<Node>("rtr-373");
  Ptr<Node> rtr374 = Names::Find<Node>("rtr-374");
  Ptr<Node> rtr375 = Names::Find<Node>("rtr-375");
  Ptr<Node> rtr376 = Names::Find<Node>("rtr-376");
  Ptr<Node> rtr377 = Names::Find<Node>("rtr-377");
  Ptr<Node> rtr378 = Names::Find<Node>("rtr-378");
  Ptr<Node> rtr379 = Names::Find<Node>("rtr-379");
  Ptr<Node> rtr380 = Names::Find<Node>("rtr-380");
  Ptr<Node> rtr381 = Names::Find<Node>("rtr-381");
  Ptr<Node> rtr382 = Names::Find<Node>("rtr-382");
  Ptr<Node> rtr383 = Names::Find<Node>("rtr-383");
  Ptr<Node> rtr384 = Names::Find<Node>("rtr-384");
  Ptr<Node> rtr385 = Names::Find<Node>("rtr-385");
  Ptr<Node> rtr386 = Names::Find<Node>("rtr-386");
  Ptr<Node> rtr387 = Names::Find<Node>("rtr-387");
  Ptr<Node> rtr388 = Names::Find<Node>("rtr-388");
  Ptr<Node> rtr389 = Names::Find<Node>("rtr-389");
  Ptr<Node> rtr390 = Names::Find<Node>("rtr-390");
  Ptr<Node> rtr391 = Names::Find<Node>("rtr-391");
  Ptr<Node> rtr392 = Names::Find<Node>("rtr-392");
  Ptr<Node> rtr393 = Names::Find<Node>("rtr-393");
  Ptr<Node> rtr394 = Names::Find<Node>("rtr-394");
  Ptr<Node> rtr395 = Names::Find<Node>("rtr-395");
  Ptr<Node> rtr396 = Names::Find<Node>("rtr-396");
  Ptr<Node> rtr397 = Names::Find<Node>("rtr-397");
  Ptr<Node> rtr398 = Names::Find<Node>("rtr-398");
  Ptr<Node> rtr399 = Names::Find<Node>("rtr-399");
  Ptr<Node> rtr400 = Names::Find<Node>("rtr-400");
  Ptr<Node> rtr401 = Names::Find<Node>("rtr-401");
  Ptr<Node> rtr402 = Names::Find<Node>("rtr-402");
  Ptr<Node> rtr403 = Names::Find<Node>("rtr-403");
  Ptr<Node> rtr404 = Names::Find<Node>("rtr-404");
  Ptr<Node> rtr405 = Names::Find<Node>("rtr-405");
  Ptr<Node> rtr406 = Names::Find<Node>("rtr-406");
  Ptr<Node> rtr407 = Names::Find<Node>("rtr-407");
  Ptr<Node> rtr408 = Names::Find<Node>("rtr-408");
  Ptr<Node> rtr409 = Names::Find<Node>("rtr-409");
  Ptr<Node> rtr410 = Names::Find<Node>("rtr-410");
  Ptr<Node> rtr411 = Names::Find<Node>("rtr-411");
  Ptr<Node> rtr412 = Names::Find<Node>("rtr-412");
  Ptr<Node> rtr413 = Names::Find<Node>("rtr-413");
  Ptr<Node> rtr414 = Names::Find<Node>("rtr-414");
  Ptr<Node> rtr415 = Names::Find<Node>("rtr-415");
  Ptr<Node> rtr416 = Names::Find<Node>("rtr-416");
  Ptr<Node> rtr417 = Names::Find<Node>("rtr-417");
  Ptr<Node> rtr418 = Names::Find<Node>("rtr-418");
  Ptr<Node> rtr419 = Names::Find<Node>("rtr-419");
  Ptr<Node> rtr420 = Names::Find<Node>("rtr-420");
  Ptr<Node> rtr421 = Names::Find<Node>("rtr-421");
  Ptr<Node> rtr422 = Names::Find<Node>("rtr-422");
  Ptr<Node> rtr423 = Names::Find<Node>("rtr-423");
  Ptr<Node> rtr424 = Names::Find<Node>("rtr-424");
  Ptr<Node> rtr425 = Names::Find<Node>("rtr-425");
  Ptr<Node> rtr426 = Names::Find<Node>("rtr-426");
  Ptr<Node> rtr427 = Names::Find<Node>("rtr-427");
  Ptr<Node> rtr428 = Names::Find<Node>("rtr-428");
  Ptr<Node> rtr429 = Names::Find<Node>("rtr-429");
  Ptr<Node> rtr430 = Names::Find<Node>("rtr-430");
  Ptr<Node> rtr431 = Names::Find<Node>("rtr-431");
  Ptr<Node> rtr432 = Names::Find<Node>("rtr-432");
  Ptr<Node> rtr433 = Names::Find<Node>("rtr-433");
  Ptr<Node> rtr434 = Names::Find<Node>("rtr-434");
  Ptr<Node> rtr435 = Names::Find<Node>("rtr-435");
  Ptr<Node> rtr436 = Names::Find<Node>("rtr-436");
  Ptr<Node> rtr437 = Names::Find<Node>("rtr-437");
  Ptr<Node> rtr438 = Names::Find<Node>("rtr-438");
  Ptr<Node> rtr439 = Names::Find<Node>("rtr-439");
  Ptr<Node> rtr440 = Names::Find<Node>("rtr-440");
  Ptr<Node> rtr441 = Names::Find<Node>("rtr-441");
  Ptr<Node> rtr442 = Names::Find<Node>("rtr-442");
  Ptr<Node> rtr443 = Names::Find<Node>("rtr-443");
  Ptr<Node> rtr444 = Names::Find<Node>("rtr-444");
  Ptr<Node> rtr445 = Names::Find<Node>("rtr-445");
  Ptr<Node> rtr446 = Names::Find<Node>("rtr-446");
  Ptr<Node> rtr447 = Names::Find<Node>("rtr-447");
  Ptr<Node> rtr448 = Names::Find<Node>("rtr-448");
  Ptr<Node> rtr449 = Names::Find<Node>("rtr-449");
  Ptr<Node> rtr450 = Names::Find<Node>("rtr-450");
  Ptr<Node> rtr451 = Names::Find<Node>("rtr-451");
  Ptr<Node> rtr452 = Names::Find<Node>("rtr-452");
  Ptr<Node> rtr453 = Names::Find<Node>("rtr-453");
  Ptr<Node> rtr454 = Names::Find<Node>("rtr-454");
  Ptr<Node> rtr455 = Names::Find<Node>("rtr-455");
  Ptr<Node> rtr456 = Names::Find<Node>("rtr-456");
  Ptr<Node> rtr457 = Names::Find<Node>("rtr-457");
  Ptr<Node> rtr458 = Names::Find<Node>("rtr-458");
  Ptr<Node> rtr459 = Names::Find<Node>("rtr-459");
  Ptr<Node> rtr460 = Names::Find<Node>("rtr-460");
  Ptr<Node> rtr461 = Names::Find<Node>("rtr-461");
  Ptr<Node> rtr462 = Names::Find<Node>("rtr-462");
  Ptr<Node> rtr463 = Names::Find<Node>("rtr-463");
  Ptr<Node> rtr464 = Names::Find<Node>("rtr-464");
  Ptr<Node> rtr465 = Names::Find<Node>("rtr-465");
  Ptr<Node> rtr466 = Names::Find<Node>("rtr-466");
  Ptr<Node> rtr467 = Names::Find<Node>("rtr-467");
  Ptr<Node> rtr468 = Names::Find<Node>("rtr-468");
  Ptr<Node> rtr469 = Names::Find<Node>("rtr-469");
  Ptr<Node> rtr470 = Names::Find<Node>("rtr-470");
  Ptr<Node> rtr471 = Names::Find<Node>("rtr-471");
  Ptr<Node> rtr472 = Names::Find<Node>("rtr-472");
  Ptr<Node> rtr473 = Names::Find<Node>("rtr-473");
  Ptr<Node> rtr474 = Names::Find<Node>("rtr-474");
  Ptr<Node> rtr475 = Names::Find<Node>("rtr-475");
  Ptr<Node> rtr476 = Names::Find<Node>("rtr-476");
  Ptr<Node> rtr477 = Names::Find<Node>("rtr-477");
  Ptr<Node> rtr478 = Names::Find<Node>("rtr-478");
  Ptr<Node> rtr479 = Names::Find<Node>("rtr-479");
  Ptr<Node> rtr480 = Names::Find<Node>("rtr-480");
  Ptr<Node> rtr481 = Names::Find<Node>("rtr-481");
  Ptr<Node> rtr482 = Names::Find<Node>("rtr-482");
  Ptr<Node> rtr483 = Names::Find<Node>("rtr-483");
  Ptr<Node> rtr484 = Names::Find<Node>("rtr-484");
  Ptr<Node> rtr485 = Names::Find<Node>("rtr-485");
  Ptr<Node> rtr486 = Names::Find<Node>("rtr-486");
  Ptr<Node> rtr487 = Names::Find<Node>("rtr-487");
  Ptr<Node> rtr488 = Names::Find<Node>("rtr-488");
  Ptr<Node> rtr489 = Names::Find<Node>("rtr-489");
  Ptr<Node> rtr490 = Names::Find<Node>("rtr-490");
  Ptr<Node> rtr491 = Names::Find<Node>("rtr-491");
  Ptr<Node> rtr492 = Names::Find<Node>("rtr-492");
  Ptr<Node> rtr493 = Names::Find<Node>("rtr-493");
  Ptr<Node> rtr494 = Names::Find<Node>("rtr-494");
  Ptr<Node> rtr495 = Names::Find<Node>("rtr-495");
  Ptr<Node> rtr496 = Names::Find<Node>("rtr-496");
  Ptr<Node> rtr497 = Names::Find<Node>("rtr-497");
  Ptr<Node> rtr498 = Names::Find<Node>("rtr-498");
  Ptr<Node> rtr499 = Names::Find<Node>("rtr-499");
  Ptr<Node> rtr500 = Names::Find<Node>("rtr-500");
  Ptr<Node> consumer = Names::Find<Node>("user");

  ndnHelper.setCsSize(0); // disable content store
  ndnHelper.Install(producer);
  ndnHelper.Install(rtr001);
  ndnHelper.Install(rtr002);
  ndnHelper.Install(rtr003);
  ndnHelper.Install(rtr004);
  ndnHelper.Install(rtr005);
  ndnHelper.Install(rtr006);
  ndnHelper.Install(rtr007);
  ndnHelper.Install(rtr008);
  ndnHelper.Install(rtr009);
  ndnHelper.Install(rtr010);
  ndnHelper.Install(rtr011);
  ndnHelper.Install(rtr012);
  ndnHelper.Install(rtr013);
  ndnHelper.Install(rtr014);
  ndnHelper.Install(rtr015);
  ndnHelper.Install(rtr016);
  ndnHelper.Install(rtr017);
  ndnHelper.Install(rtr018);
  ndnHelper.Install(rtr019);
  ndnHelper.Install(rtr020);
  ndnHelper.Install(rtr021);
  ndnHelper.Install(rtr022);
  ndnHelper.Install(rtr023);
  ndnHelper.Install(rtr024);
  ndnHelper.Install(rtr025);
  ndnHelper.Install(rtr026);
  ndnHelper.Install(rtr027);
  ndnHelper.Install(rtr028);
  ndnHelper.Install(rtr029);
  ndnHelper.Install(rtr030);
  ndnHelper.Install(rtr031);
  ndnHelper.Install(rtr032);
  ndnHelper.Install(rtr033);
  ndnHelper.Install(rtr034);
  ndnHelper.Install(rtr035);
  ndnHelper.Install(rtr036);
  ndnHelper.Install(rtr037);
  ndnHelper.Install(rtr038);
  ndnHelper.Install(rtr039);
  ndnHelper.Install(rtr040);
  ndnHelper.Install(rtr041);
  ndnHelper.Install(rtr042);
  ndnHelper.Install(rtr043);
  ndnHelper.Install(rtr044);
  ndnHelper.Install(rtr045);
  ndnHelper.Install(rtr046);
  ndnHelper.Install(rtr047);
  ndnHelper.Install(rtr048);
  ndnHelper.Install(rtr049);
  ndnHelper.Install(rtr050);
  ndnHelper.Install(rtr051);
  ndnHelper.Install(rtr052);
  ndnHelper.Install(rtr053);
  ndnHelper.Install(rtr054);
  ndnHelper.Install(rtr055);
  ndnHelper.Install(rtr056);
  ndnHelper.Install(rtr057);
  ndnHelper.Install(rtr058);
  ndnHelper.Install(rtr059);
  ndnHelper.Install(rtr060);
  ndnHelper.Install(rtr061);
  ndnHelper.Install(rtr062);
  ndnHelper.Install(rtr063);
  ndnHelper.Install(rtr064);
  ndnHelper.Install(rtr065);
  ndnHelper.Install(rtr066);
  ndnHelper.Install(rtr067);
  ndnHelper.Install(rtr068);
  ndnHelper.Install(rtr069);
  ndnHelper.Install(rtr070);
  ndnHelper.Install(rtr071);
  ndnHelper.Install(rtr072);
  ndnHelper.Install(rtr073);
  ndnHelper.Install(rtr074);
  ndnHelper.Install(rtr075);
  ndnHelper.Install(rtr076);
  ndnHelper.Install(rtr077);
  ndnHelper.Install(rtr078);
  ndnHelper.Install(rtr079);
  ndnHelper.Install(rtr080);
  ndnHelper.Install(rtr081);
  ndnHelper.Install(rtr082);
  ndnHelper.Install(rtr083);
  ndnHelper.Install(rtr084);
  ndnHelper.Install(rtr085);
  ndnHelper.Install(rtr086);
  ndnHelper.Install(rtr087);
  ndnHelper.Install(rtr088);
  ndnHelper.Install(rtr089);
  ndnHelper.Install(rtr090);
  ndnHelper.Install(rtr091);
  ndnHelper.Install(rtr092);
  ndnHelper.Install(rtr093);
  ndnHelper.Install(rtr094);
  ndnHelper.Install(rtr095);
  ndnHelper.Install(rtr096);
  ndnHelper.Install(rtr097);
  ndnHelper.Install(rtr098);
  ndnHelper.Install(rtr099);
  ndnHelper.Install(rtr100);
  ndnHelper.Install(rtr101);
  ndnHelper.Install(rtr102);
  ndnHelper.Install(rtr103);
  ndnHelper.Install(rtr104);
  ndnHelper.Install(rtr105);
  ndnHelper.Install(rtr106);
  ndnHelper.Install(rtr107);
  ndnHelper.Install(rtr108);
  ndnHelper.Install(rtr109);
  ndnHelper.Install(rtr110);
  ndnHelper.Install(rtr111);
  ndnHelper.Install(rtr112);
  ndnHelper.Install(rtr113);
  ndnHelper.Install(rtr114);
  ndnHelper.Install(rtr115);
  ndnHelper.Install(rtr116);
  ndnHelper.Install(rtr117);
  ndnHelper.Install(rtr118);
  ndnHelper.Install(rtr119);
  ndnHelper.Install(rtr120);
  ndnHelper.Install(rtr121);
  ndnHelper.Install(rtr122);
  ndnHelper.Install(rtr123);
  ndnHelper.Install(rtr124);
  ndnHelper.Install(rtr125);
  ndnHelper.Install(rtr126);
  ndnHelper.Install(rtr127);
  ndnHelper.Install(rtr128);
  ndnHelper.Install(rtr129);
  ndnHelper.Install(rtr130);
  ndnHelper.Install(rtr131);
  ndnHelper.Install(rtr132);
  ndnHelper.Install(rtr133);
  ndnHelper.Install(rtr134);
  ndnHelper.Install(rtr135);
  ndnHelper.Install(rtr136);
  ndnHelper.Install(rtr137);
  ndnHelper.Install(rtr138);
  ndnHelper.Install(rtr139);
  ndnHelper.Install(rtr140);
  ndnHelper.Install(rtr141);
  ndnHelper.Install(rtr142);
  ndnHelper.Install(rtr143);
  ndnHelper.Install(rtr144);
  ndnHelper.Install(rtr145);
  ndnHelper.Install(rtr146);
  ndnHelper.Install(rtr147);
  ndnHelper.Install(rtr148);
  ndnHelper.Install(rtr149);
  ndnHelper.Install(rtr150);
  ndnHelper.Install(rtr151);
  ndnHelper.Install(rtr152);
  ndnHelper.Install(rtr153);
  ndnHelper.Install(rtr154);
  ndnHelper.Install(rtr155);
  ndnHelper.Install(rtr156);
  ndnHelper.Install(rtr157);
  ndnHelper.Install(rtr158);
  ndnHelper.Install(rtr159);
  ndnHelper.Install(rtr160);
  ndnHelper.Install(rtr161);
  ndnHelper.Install(rtr162);
  ndnHelper.Install(rtr163);
  ndnHelper.Install(rtr164);
  ndnHelper.Install(rtr165);
  ndnHelper.Install(rtr166);
  ndnHelper.Install(rtr167);
  ndnHelper.Install(rtr168);
  ndnHelper.Install(rtr169);
  ndnHelper.Install(rtr170);
  ndnHelper.Install(rtr171);
  ndnHelper.Install(rtr172);
  ndnHelper.Install(rtr173);
  ndnHelper.Install(rtr174);
  ndnHelper.Install(rtr175);
  ndnHelper.Install(rtr176);
  ndnHelper.Install(rtr177);
  ndnHelper.Install(rtr178);
  ndnHelper.Install(rtr179);
  ndnHelper.Install(rtr180);
  ndnHelper.Install(rtr181);
  ndnHelper.Install(rtr182);
  ndnHelper.Install(rtr183);
  ndnHelper.Install(rtr184);
  ndnHelper.Install(rtr185);
  ndnHelper.Install(rtr186);
  ndnHelper.Install(rtr187);
  ndnHelper.Install(rtr188);
  ndnHelper.Install(rtr189);
  ndnHelper.Install(rtr190);
  ndnHelper.Install(rtr191);
  ndnHelper.Install(rtr192);
  ndnHelper.Install(rtr193);
  ndnHelper.Install(rtr194);
  ndnHelper.Install(rtr195);
  ndnHelper.Install(rtr196);
  ndnHelper.Install(rtr197);
  ndnHelper.Install(rtr198);
  ndnHelper.Install(rtr199);
  ndnHelper.Install(rtr200);
  ndnHelper.Install(rtr201);
  ndnHelper.Install(rtr202);
  ndnHelper.Install(rtr203);
  ndnHelper.Install(rtr204);
  ndnHelper.Install(rtr205);
  ndnHelper.Install(rtr206);
  ndnHelper.Install(rtr207);
  ndnHelper.Install(rtr208);
  ndnHelper.Install(rtr209);
  ndnHelper.Install(rtr210);
  ndnHelper.Install(rtr211);
  ndnHelper.Install(rtr212);
  ndnHelper.Install(rtr213);
  ndnHelper.Install(rtr214);
  ndnHelper.Install(rtr215);
  ndnHelper.Install(rtr216);
  ndnHelper.Install(rtr217);
  ndnHelper.Install(rtr218);
  ndnHelper.Install(rtr219);
  ndnHelper.Install(rtr220);
  ndnHelper.Install(rtr221);
  ndnHelper.Install(rtr222);
  ndnHelper.Install(rtr223);
  ndnHelper.Install(rtr224);
  ndnHelper.Install(rtr225);
  ndnHelper.Install(rtr226);
  ndnHelper.Install(rtr227);
  ndnHelper.Install(rtr228);
  ndnHelper.Install(rtr229);
  ndnHelper.Install(rtr230);
  ndnHelper.Install(rtr231);
  ndnHelper.Install(rtr232);
  ndnHelper.Install(rtr233);
  ndnHelper.Install(rtr234);
  ndnHelper.Install(rtr235);
  ndnHelper.Install(rtr236);
  ndnHelper.Install(rtr237);
  ndnHelper.Install(rtr238);
  ndnHelper.Install(rtr239);
  ndnHelper.Install(rtr240);
  ndnHelper.Install(rtr241);
  ndnHelper.Install(rtr242);
  ndnHelper.Install(rtr243);
  ndnHelper.Install(rtr244);
  ndnHelper.Install(rtr245);
  ndnHelper.Install(rtr246);
  ndnHelper.Install(rtr247);
  ndnHelper.Install(rtr248);
  ndnHelper.Install(rtr249);
  ndnHelper.Install(rtr250);
  ndnHelper.Install(rtr251);
  ndnHelper.Install(rtr252);
  ndnHelper.Install(rtr253);
  ndnHelper.Install(rtr254);
  ndnHelper.Install(rtr255);
  ndnHelper.Install(rtr256);
  ndnHelper.Install(rtr257);
  ndnHelper.Install(rtr258);
  ndnHelper.Install(rtr259);
  ndnHelper.Install(rtr260);
  ndnHelper.Install(rtr261);
  ndnHelper.Install(rtr262);
  ndnHelper.Install(rtr263);
  ndnHelper.Install(rtr264);
  ndnHelper.Install(rtr265);
  ndnHelper.Install(rtr266);
  ndnHelper.Install(rtr267);
  ndnHelper.Install(rtr268);
  ndnHelper.Install(rtr269);
  ndnHelper.Install(rtr270);
  ndnHelper.Install(rtr271);
  ndnHelper.Install(rtr272);
  ndnHelper.Install(rtr273);
  ndnHelper.Install(rtr274);
  ndnHelper.Install(rtr275);
  ndnHelper.Install(rtr276);
  ndnHelper.Install(rtr277);
  ndnHelper.Install(rtr278);
  ndnHelper.Install(rtr279);
  ndnHelper.Install(rtr280);
  ndnHelper.Install(rtr281);
  ndnHelper.Install(rtr282);
  ndnHelper.Install(rtr283);
  ndnHelper.Install(rtr284);
  ndnHelper.Install(rtr285);
  ndnHelper.Install(rtr286);
  ndnHelper.Install(rtr287);
  ndnHelper.Install(rtr288);
  ndnHelper.Install(rtr289);
  ndnHelper.Install(rtr290);
  ndnHelper.Install(rtr291);
  ndnHelper.Install(rtr292);
  ndnHelper.Install(rtr293);
  ndnHelper.Install(rtr294);
  ndnHelper.Install(rtr295);
  ndnHelper.Install(rtr296);
  ndnHelper.Install(rtr297);
  ndnHelper.Install(rtr298);
  ndnHelper.Install(rtr299);
  ndnHelper.Install(rtr300);
  ndnHelper.Install(rtr301);
  ndnHelper.Install(rtr302);
  ndnHelper.Install(rtr303);
  ndnHelper.Install(rtr304);
  ndnHelper.Install(rtr305);
  ndnHelper.Install(rtr306);
  ndnHelper.Install(rtr307);
  ndnHelper.Install(rtr308);
  ndnHelper.Install(rtr309);
  ndnHelper.Install(rtr310);
  ndnHelper.Install(rtr311);
  ndnHelper.Install(rtr312);
  ndnHelper.Install(rtr313);
  ndnHelper.Install(rtr314);
  ndnHelper.Install(rtr315);
  ndnHelper.Install(rtr316);
  ndnHelper.Install(rtr317);
  ndnHelper.Install(rtr318);
  ndnHelper.Install(rtr319);
  ndnHelper.Install(rtr320);
  ndnHelper.Install(rtr321);
  ndnHelper.Install(rtr322);
  ndnHelper.Install(rtr323);
  ndnHelper.Install(rtr324);
  ndnHelper.Install(rtr325);
  ndnHelper.Install(rtr326);
  ndnHelper.Install(rtr327);
  ndnHelper.Install(rtr328);
  ndnHelper.Install(rtr329);
  ndnHelper.Install(rtr330);
  ndnHelper.Install(rtr331);
  ndnHelper.Install(rtr332);
  ndnHelper.Install(rtr333);
  ndnHelper.Install(rtr334);
  ndnHelper.Install(rtr335);
  ndnHelper.Install(rtr336);
  ndnHelper.Install(rtr337);
  ndnHelper.Install(rtr338);
  ndnHelper.Install(rtr339);
  ndnHelper.Install(rtr340);
  ndnHelper.Install(rtr341);
  ndnHelper.Install(rtr342);
  ndnHelper.Install(rtr343);
  ndnHelper.Install(rtr344);
  ndnHelper.Install(rtr345);
  ndnHelper.Install(rtr346);
  ndnHelper.Install(rtr347);
  ndnHelper.Install(rtr348);
  ndnHelper.Install(rtr349);
  ndnHelper.Install(rtr350);
  ndnHelper.Install(rtr351);
  ndnHelper.Install(rtr352);
  ndnHelper.Install(rtr353);
  ndnHelper.Install(rtr354);
  ndnHelper.Install(rtr355);
  ndnHelper.Install(rtr356);
  ndnHelper.Install(rtr357);
  ndnHelper.Install(rtr358);
  ndnHelper.Install(rtr359);
  ndnHelper.Install(rtr360);
  ndnHelper.Install(rtr361);
  ndnHelper.Install(rtr362);
  ndnHelper.Install(rtr363);
  ndnHelper.Install(rtr364);
  ndnHelper.Install(rtr365);
  ndnHelper.Install(rtr366);
  ndnHelper.Install(rtr367);
  ndnHelper.Install(rtr368);
  ndnHelper.Install(rtr369);
  ndnHelper.Install(rtr370);
  ndnHelper.Install(rtr371);
  ndnHelper.Install(rtr372);
  ndnHelper.Install(rtr373);
  ndnHelper.Install(rtr374);
  ndnHelper.Install(rtr375);
  ndnHelper.Install(rtr376);
  ndnHelper.Install(rtr377);
  ndnHelper.Install(rtr378);
  ndnHelper.Install(rtr379);
  ndnHelper.Install(rtr380);
  ndnHelper.Install(rtr381);
  ndnHelper.Install(rtr382);
  ndnHelper.Install(rtr383);
  ndnHelper.Install(rtr384);
  ndnHelper.Install(rtr385);
  ndnHelper.Install(rtr386);
  ndnHelper.Install(rtr387);
  ndnHelper.Install(rtr388);
  ndnHelper.Install(rtr389);
  ndnHelper.Install(rtr390);
  ndnHelper.Install(rtr391);
  ndnHelper.Install(rtr392);
  ndnHelper.Install(rtr393);
  ndnHelper.Install(rtr394);
  ndnHelper.Install(rtr395);
  ndnHelper.Install(rtr396);
  ndnHelper.Install(rtr397);
  ndnHelper.Install(rtr398);
  ndnHelper.Install(rtr399);
  ndnHelper.Install(rtr400);
  ndnHelper.Install(rtr401);
  ndnHelper.Install(rtr402);
  ndnHelper.Install(rtr403);
  ndnHelper.Install(rtr404);
  ndnHelper.Install(rtr405);
  ndnHelper.Install(rtr406);
  ndnHelper.Install(rtr407);
  ndnHelper.Install(rtr408);
  ndnHelper.Install(rtr409);
  ndnHelper.Install(rtr410);
  ndnHelper.Install(rtr411);
  ndnHelper.Install(rtr412);
  ndnHelper.Install(rtr413);
  ndnHelper.Install(rtr414);
  ndnHelper.Install(rtr415);
  ndnHelper.Install(rtr416);
  ndnHelper.Install(rtr417);
  ndnHelper.Install(rtr418);
  ndnHelper.Install(rtr419);
  ndnHelper.Install(rtr420);
  ndnHelper.Install(rtr421);
  ndnHelper.Install(rtr422);
  ndnHelper.Install(rtr423);
  ndnHelper.Install(rtr424);
  ndnHelper.Install(rtr425);
  ndnHelper.Install(rtr426);
  ndnHelper.Install(rtr427);
  ndnHelper.Install(rtr428);
  ndnHelper.Install(rtr429);
  ndnHelper.Install(rtr430);
  ndnHelper.Install(rtr431);
  ndnHelper.Install(rtr432);
  ndnHelper.Install(rtr433);
  ndnHelper.Install(rtr434);
  ndnHelper.Install(rtr435);
  ndnHelper.Install(rtr436);
  ndnHelper.Install(rtr437);
  ndnHelper.Install(rtr438);
  ndnHelper.Install(rtr439);
  ndnHelper.Install(rtr440);
  ndnHelper.Install(rtr441);
  ndnHelper.Install(rtr442);
  ndnHelper.Install(rtr443);
  ndnHelper.Install(rtr444);
  ndnHelper.Install(rtr445);
  ndnHelper.Install(rtr446);
  ndnHelper.Install(rtr447);
  ndnHelper.Install(rtr448);
  ndnHelper.Install(rtr449);
  ndnHelper.Install(rtr450);
  ndnHelper.Install(rtr451);
  ndnHelper.Install(rtr452);
  ndnHelper.Install(rtr453);
  ndnHelper.Install(rtr454);
  ndnHelper.Install(rtr455);
  ndnHelper.Install(rtr456);
  ndnHelper.Install(rtr457);
  ndnHelper.Install(rtr458);
  ndnHelper.Install(rtr459);
  ndnHelper.Install(rtr460);
  ndnHelper.Install(rtr461);
  ndnHelper.Install(rtr462);
  ndnHelper.Install(rtr463);
  ndnHelper.Install(rtr464);
  ndnHelper.Install(rtr465);
  ndnHelper.Install(rtr466);
  ndnHelper.Install(rtr467);
  ndnHelper.Install(rtr468);
  ndnHelper.Install(rtr469);
  ndnHelper.Install(rtr470);
  ndnHelper.Install(rtr471);
  ndnHelper.Install(rtr472);
  ndnHelper.Install(rtr473);
  ndnHelper.Install(rtr474);
  ndnHelper.Install(rtr475);
  ndnHelper.Install(rtr476);
  ndnHelper.Install(rtr477);
  ndnHelper.Install(rtr478);
  ndnHelper.Install(rtr479);
  ndnHelper.Install(rtr480);
  ndnHelper.Install(rtr481);
  ndnHelper.Install(rtr482);
  ndnHelper.Install(rtr483);
  ndnHelper.Install(rtr484);
  ndnHelper.Install(rtr485);
  ndnHelper.Install(rtr486);
  ndnHelper.Install(rtr487);
  ndnHelper.Install(rtr488);
  ndnHelper.Install(rtr489);
  ndnHelper.Install(rtr490);
  ndnHelper.Install(rtr491);
  ndnHelper.Install(rtr492);
  ndnHelper.Install(rtr493);
  ndnHelper.Install(rtr494);
  ndnHelper.Install(rtr495);
  ndnHelper.Install(rtr496);
  ndnHelper.Install(rtr497);
  ndnHelper.Install(rtr498);
  ndnHelper.Install(rtr499);
  ndnHelper.Install(rtr500);
  ndnHelper.Install(consumer);



  std::string Prefix(PREFIX);

  // Choosing forwarding strategy
  //ndn::StrategyChoiceHelper::InstallAll("/prefix", "/localhost/nfd/strategy/best-route");
  //ndn::StrategyChoiceHelper::InstallAll("/prefix", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-001", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-002", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-003", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-004", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-005", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-006", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-007", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-008", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-009", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-010", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-011", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-012", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-013", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-014", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-015", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-016", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-017", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-018", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-019", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-020", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-021", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-022", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-023", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-024", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-025", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-026", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-027", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-028", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-029", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-030", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-031", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-032", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-033", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-034", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-035", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-036", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-037", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-038", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-039", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-040", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-041", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-042", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-043", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-044", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-045", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-046", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-047", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-048", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-049", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-050", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-051", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-052", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-053", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-054", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-055", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-056", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-057", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-058", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-059", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-060", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-061", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-062", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-063", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-064", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-065", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-066", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-067", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-068", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-069", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-070", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-071", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-072", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-073", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-074", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-075", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-076", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-077", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-078", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-079", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-080", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-081", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-082", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-083", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-084", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-085", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-086", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-087", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-088", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-089", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-090", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-091", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-092", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-093", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-094", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-095", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-096", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-097", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-098", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-099", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/serviceCPM-100", "/localhost/nfd/strategy/multicast");
  ndn::StrategyChoiceHelper::InstallAll(Prefix + "/sensor", "/localhost/nfd/strategy/multicast");

  // Installing global routing interface on all nodes
  //ndn::GlobalRoutingHelper ndnGlobalRoutingHelper;
  //ndnGlobalRoutingHelper.InstallAll();

  // Getting containers for the consumer/producer
  //Ptr<Node> consumer = Names::Find<Node>("user");
  //Ptr<Node> producer = Names::Find<Node>("sensor");
  //Ptr<Node> producer = Names::Find<Node>("rtr-1");

 


  // Installing applications

  // Custom App for Sensor(Producer)
  ndn::AppHelper sensorApp("CustomAppProducer");
  sensorApp.SetPrefix(Prefix);
  sensorApp.SetAttribute("Service", StringValue("sensor"));
  sensorApp.Install(producer).Start(Seconds(0));

  // Custom App for routers
  ndn::AppHelper routerApp("DagForwarderApp");
  routerApp.SetPrefix(Prefix);
  routerApp.SetAttribute("Service", StringValue("serviceCPM-001"));
  routerApp.Install(rtr005).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-002"));
  routerApp.Install(rtr010).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-003"));
  routerApp.Install(rtr015).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-004"));
  routerApp.Install(rtr020).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-005"));
  routerApp.Install(rtr025).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-006"));
  routerApp.Install(rtr030).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-007"));
  routerApp.Install(rtr035).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-008"));
  routerApp.Install(rtr040).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-009"));
  routerApp.Install(rtr045).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-010"));
  routerApp.Install(rtr050).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-011"));
  routerApp.Install(rtr055).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-012"));
  routerApp.Install(rtr060).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-013"));
  routerApp.Install(rtr065).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-014"));
  routerApp.Install(rtr070).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-015"));
  routerApp.Install(rtr075).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-016"));
  routerApp.Install(rtr080).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-017"));
  routerApp.Install(rtr085).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-018"));
  routerApp.Install(rtr090).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-019"));
  routerApp.Install(rtr095).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-020"));
  routerApp.Install(rtr100).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-021"));
  routerApp.Install(rtr105).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-022"));
  routerApp.Install(rtr110).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-023"));
  routerApp.Install(rtr115).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-024"));
  routerApp.Install(rtr120).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-025"));
  routerApp.Install(rtr125).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-026"));
  routerApp.Install(rtr130).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-027"));
  routerApp.Install(rtr135).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-028"));
  routerApp.Install(rtr140).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-029"));
  routerApp.Install(rtr145).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-030"));
  routerApp.Install(rtr150).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-031"));
  routerApp.Install(rtr155).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-032"));
  routerApp.Install(rtr160).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-033"));
  routerApp.Install(rtr165).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-034"));
  routerApp.Install(rtr170).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-035"));
  routerApp.Install(rtr175).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-036"));
  routerApp.Install(rtr180).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-037"));
  routerApp.Install(rtr185).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-038"));
  routerApp.Install(rtr190).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-039"));
  routerApp.Install(rtr195).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-040"));
  routerApp.Install(rtr200).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-041"));
  routerApp.Install(rtr205).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-042"));
  routerApp.Install(rtr210).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-043"));
  routerApp.Install(rtr215).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-044"));
  routerApp.Install(rtr220).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-045"));
  routerApp.Install(rtr225).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-046"));
  routerApp.Install(rtr230).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-047"));
  routerApp.Install(rtr235).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-048"));
  routerApp.Install(rtr240).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-049"));
  routerApp.Install(rtr245).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-050"));
  routerApp.Install(rtr250).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-051"));
  routerApp.Install(rtr255).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-052"));
  routerApp.Install(rtr260).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-053"));
  routerApp.Install(rtr265).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-054"));
  routerApp.Install(rtr270).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-055"));
  routerApp.Install(rtr275).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-056"));
  routerApp.Install(rtr280).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-057"));
  routerApp.Install(rtr285).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-058"));
  routerApp.Install(rtr290).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-059"));
  routerApp.Install(rtr295).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-060"));
  routerApp.Install(rtr300).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-061"));
  routerApp.Install(rtr305).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-062"));
  routerApp.Install(rtr310).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-063"));
  routerApp.Install(rtr315).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-064"));
  routerApp.Install(rtr320).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-065"));
  routerApp.Install(rtr325).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-066"));
  routerApp.Install(rtr330).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-067"));
  routerApp.Install(rtr335).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-068"));
  routerApp.Install(rtr340).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-069"));
  routerApp.Install(rtr345).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-070"));
  routerApp.Install(rtr350).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-071"));
  routerApp.Install(rtr355).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-072"));
  routerApp.Install(rtr360).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-073"));
  routerApp.Install(rtr365).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-074"));
  routerApp.Install(rtr370).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-075"));
  routerApp.Install(rtr375).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-076"));
  routerApp.Install(rtr380).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-077"));
  routerApp.Install(rtr385).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-078"));
  routerApp.Install(rtr390).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-079"));
  routerApp.Install(rtr395).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-080"));
  routerApp.Install(rtr400).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-081"));
  routerApp.Install(rtr405).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-082"));
  routerApp.Install(rtr410).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-083"));
  routerApp.Install(rtr415).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-084"));
  routerApp.Install(rtr420).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-085"));
  routerApp.Install(rtr425).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-086"));
  routerApp.Install(rtr430).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-087"));
  routerApp.Install(rtr435).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-088"));
  routerApp.Install(rtr440).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-089"));
  routerApp.Install(rtr445).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-090"));
  routerApp.Install(rtr450).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-091"));
  routerApp.Install(rtr455).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-092"));
  routerApp.Install(rtr460).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-093"));
  routerApp.Install(rtr465).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-094"));
  routerApp.Install(rtr470).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-095"));
  routerApp.Install(rtr475).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-096"));
  routerApp.Install(rtr480).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-097"));
  routerApp.Install(rtr485).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-098"));
  routerApp.Install(rtr490).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-099"));
  routerApp.Install(rtr495).Start(Seconds(0));
  routerApp.SetAttribute("Service", StringValue("serviceCPM-100"));
  routerApp.Install(rtr500).Start(Seconds(0));

  // Custom App for User(Consumer)
  ndn::AppHelper userApp("CustomAppConsumer");
  userApp.SetPrefix(Prefix);
  userApp.SetAttribute("Service", StringValue("consumer"));
  userApp.SetAttribute("Workflow", StringValue("workflows/cpm-100_x.json"));
  userApp.SetAttribute("Orchestrate", UintegerValue(0));
  userApp.Install(consumer).Start(Seconds(0));



  Simulator::Stop(Seconds(240.1));


  Simulator::Run();
  Simulator::Destroy();

  return 0;
}

} // namespace ns3

int
main(int argc, char* argv[])
{
  return ns3::main(argc, argv);
}
